name: Prebuild

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   arch: x64
          #   - os: macos-latest
           #    arch: arm64
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    permissions:  write-all
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'
      - name: Install Dependencies
        run: npm install
      - name: Build and Upload Prebuild
        run: |
          npm run prebuild -- -t 16.20.2 --arch ${{ matrix.arch }} -u ${{ secrets.GITHUB_TOKEN }}
        env:
          PREBUILD_TOKEN: ${{ secrets.GITHUB_TOKEN }}
